name: gauthtest

on:
  push:
    branches:
      - master

jobs:
 my_ci_part:
   runs-on: ubuntu-latest
   
   steps: 
    - name: git clone repo
      uses: actions/checkout@v2
      
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/178272902313/locations/global/workloadIdentityPools/my-pool/providers/git'
        service_account: 'aty-tst@aty-tst-350008.iam.gserviceaccount.com'
        
    - name: GCP instance creation
      run: |
           terraform init
           
