name: gauthtest

on:
  push:
    branches:
      - main
      
permissions:
  id-token: write

jobs:
 my_ci_part:
   runs-on: ubuntu-latest
   
   steps: 
    - name: git clone repo
      uses: actions/checkout@v2
      
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
        create_credentials_file: 'true'
        workload_identity_provider: 'projects/178272902313/locations/global/workloadIdentityPools/google-github/providers/git-provider'
        service_account: 'aty-tst@aty-tst-350008.iam.gserviceaccount.com'
        
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file='${{ steps.auth.outputs.credentials_file_path }}'
        gcloud config set project aty-tst-350008

    - name: GCP instance creation
      run: |
           terraform init
           terraform apply -auto-approve
      env: 
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
