name: simpletst

on:
 workflow_dispatch:
 
jobs:
  job1:
    name: simpletst
    runs-on: ubuntu-latest
    steps:
    - name: define variable
      run: |
       dif="variable1"
       echo "$dif"
      
    - name: check variable
      run: |
       echo "$dif"
  job2:
    name: checktest
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: get variable
      run: |
       echo "$dif"
    
