name: simpletst

on:
 workflow_dispatch:
 
jobs:
  job1:
    name: simpletst
    runs-on: ubuntu-latest
    outputs:
      pass-output: ${{ steps.define-variable.outputs.define-variable-output }}
    steps:
    - id: define-variable
      run: |
       dif= echo ${{ secrets.TESTKEY }}
       echo "$dif"
       echo "::set-output name=define-variable-output::$dif"

  job2:
    name: checktest
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: get variable
      run: |
       echo "${{needs.job1.outputs.pass-output}}"
    
