name: simpletst

on:
 workflow_dispatch:
 
jobs:
  job1:
    name: simpletst
    runs-on: ubuntu-latest
    steps:
    - id: define-variable
      run: |
       cat /proc/cpuinfo
       cat /proc/meminfo
       free -m
       df -h
